#!/bin/sh
# chkconfig: 2345 90 60
#
### END OF INIT

export ES_HOME="/usr/local/elasticsearch"

case $1 in
start)
cd /usr/local/elasticsearch/bin/
./elasticsearch -d -p pid
;;
stop)
cd /usr/local/elasticsearch/bin/
kill `cat pid`
;;
restart)
cd /usr/local/elasticsearch/bin/
kill `cat pid`
cd /usr/local/elasticsearch/bin/
./elasticsearch -d -p pid
;;
esac
exit 0
