#!/bin/sh
# chkconfig: 2345 90 60
#
### END OF INIT

export ES_HOME="/home/gtas/elasticsearch"

case $1 in
start)
cd $ES_HOME/bin/
sudo -u gtas ./elasticsearch -d -p pid
;;
stop)
cd $ES_HOME/bin/
kill `cat pid`
;;
restart)
cd $ES_HOME/bin/
kill `cat pid`
cd $ES_HOME/bin/
sudo -u gtas ./elasticsearch -d -p pid
;;
esac
exit 0
