#!/bin/sh
# chkconfig: 2345 90 60
#
### END OF INIT

export REDIS_HOME="/usr/local/redis"

DAEMON=/usr/local/redis/src/redis-server
DAEMON_ARGS=/usr/local/redis/redis.conf
NAME=redis-server
DESC=redis-server
PIDFILE=/var/run/redis_6379.pid

set -e

case $1 in
start)
    echo -n "Staring $DESC: "

    $DAEMON $DAEMON_ARGS
;;
stop)
    echo -n "Stopping $DESC: "
    kill `cat $PIDFILE`
    rm -f $PIDFILE
;;
restart|force-reload)
${0} stop
${0} start 
;;
*)
 echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload}" >&2
 exit 1
 ;;
esac
exit 0
